# Generated by Django 4.1.3 on 2023-04-13 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 4, 13, 0, 0)),
            preserve_default=False,
        ),
    ]
